// Generated by gencpp from file yolov8_msgs/ConfidenceScore.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_CONFIDENCESCORE_H
#define YOLOV8_MSGS_MESSAGE_CONFIDENCESCORE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace yolov8_msgs
{
template <class ContainerAllocator>
struct ConfidenceScore_
{
  typedef ConfidenceScore_<ContainerAllocator> Type;

  ConfidenceScore_()
    : header()
    , conf(0.0)  {
    }
  ConfidenceScore_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , conf(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _conf_type;
  _conf_type conf;





  typedef boost::shared_ptr< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> const> ConstPtr;

}; // struct ConfidenceScore_

typedef ::yolov8_msgs::ConfidenceScore_<std::allocator<void> > ConfidenceScore;

typedef boost::shared_ptr< ::yolov8_msgs::ConfidenceScore > ConfidenceScorePtr;
typedef boost::shared_ptr< ::yolov8_msgs::ConfidenceScore const> ConfidenceScoreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator1> & lhs, const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.conf == rhs.conf;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator1> & lhs, const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86ad5b8fcf7de5c78bec638d1ee58116";
  }

  static const char* value(const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86ad5b8fcf7de5c7ULL;
  static const uint64_t static_value2 = 0x8bec638d1ee58116ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/ConfidenceScore";
  }

  static const char* value(const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header #adds timestamp \n"
"float64 conf\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.conf);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfidenceScore_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::ConfidenceScore_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::ConfidenceScore_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "conf: ";
    Printer<double>::stream(s, indent + "  ", v.conf);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_CONFIDENCESCORE_H
