// Generated by gencpp from file yolov8_msgs/CustomMsg.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_CUSTOMMSG_H
#define YOLOV8_MSGS_MESSAGE_CUSTOMMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace yolov8_msgs
{
template <class ContainerAllocator>
struct CustomMsg_
{
  typedef CustomMsg_<ContainerAllocator> Type;

  CustomMsg_()
    : header()
    , yolo_output(0.0)
    , optitrack_output()  {
    }
  CustomMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yolo_output(0.0)
    , optitrack_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _yolo_output_type;
  _yolo_output_type yolo_output;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _optitrack_output_type;
  _optitrack_output_type optitrack_output;





  typedef boost::shared_ptr< ::yolov8_msgs::CustomMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::CustomMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMsg_

typedef ::yolov8_msgs::CustomMsg_<std::allocator<void> > CustomMsg;

typedef boost::shared_ptr< ::yolov8_msgs::CustomMsg > CustomMsgPtr;
typedef boost::shared_ptr< ::yolov8_msgs::CustomMsg const> CustomMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::CustomMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::CustomMsg_<ContainerAllocator1> & lhs, const ::yolov8_msgs::CustomMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yolo_output == rhs.yolo_output &&
    lhs.optitrack_output == rhs.optitrack_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::CustomMsg_<ContainerAllocator1> & lhs, const ::yolov8_msgs::CustomMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::CustomMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::CustomMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::CustomMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d09e9aa5098510534f16d66c34f02b";
  }

  static const char* value(const ::yolov8_msgs::CustomMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d09e9aa5098510ULL;
  static const uint64_t static_value2 = 0x534f16d66c34f02bULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/CustomMsg";
  }

  static const char* value(const ::yolov8_msgs::CustomMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CustomMsg.msg\n"
"std_msgs/Header header\n"
"float64 yolo_output\n"
"geometry_msgs/PoseStamped optitrack_output\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::yolov8_msgs::CustomMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yolo_output);
      stream.next(m.optitrack_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::CustomMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::CustomMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yolo_output: ";
    Printer<double>::stream(s, indent + "  ", v.yolo_output);
    s << indent << "optitrack_output: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.optitrack_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_CUSTOMMSG_H
