// Generated by gencpp from file yolov8_msgs/PlotCoordinates.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_PLOTCOORDINATES_H
#define YOLOV8_MSGS_MESSAGE_PLOTCOORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov8_msgs
{
template <class ContainerAllocator>
struct PlotCoordinates_
{
  typedef PlotCoordinates_<ContainerAllocator> Type;

  PlotCoordinates_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  PlotCoordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> const> ConstPtr;

}; // struct PlotCoordinates_

typedef ::yolov8_msgs::PlotCoordinates_<std::allocator<void> > PlotCoordinates;

typedef boost::shared_ptr< ::yolov8_msgs::PlotCoordinates > PlotCoordinatesPtr;
typedef boost::shared_ptr< ::yolov8_msgs::PlotCoordinates const> PlotCoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator1> & lhs, const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator1> & lhs, const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/PlotCoordinates";
  }

  static const char* value(const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlotCoordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::PlotCoordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::PlotCoordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_PLOTCOORDINATES_H
