// Generated by gencpp from file yolov8_msgs/Yolov8Inference.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_YOLOV8INFERENCE_H
#define YOLOV8_MSGS_MESSAGE_YOLOV8INFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <yolov8_msgs/InferenceResult.h>

namespace yolov8_msgs
{
template <class ContainerAllocator>
struct Yolov8Inference_
{
  typedef Yolov8Inference_<ContainerAllocator> Type;

  Yolov8Inference_()
    : header()
    , yolov8_inference()  {
    }
  Yolov8Inference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yolov8_inference(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::yolov8_msgs::InferenceResult_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::yolov8_msgs::InferenceResult_<ContainerAllocator> >> _yolov8_inference_type;
  _yolov8_inference_type yolov8_inference;





  typedef boost::shared_ptr< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> const> ConstPtr;

}; // struct Yolov8Inference_

typedef ::yolov8_msgs::Yolov8Inference_<std::allocator<void> > Yolov8Inference;

typedef boost::shared_ptr< ::yolov8_msgs::Yolov8Inference > Yolov8InferencePtr;
typedef boost::shared_ptr< ::yolov8_msgs::Yolov8Inference const> Yolov8InferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator1> & lhs, const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yolov8_inference == rhs.yolov8_inference;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator1> & lhs, const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "081ce2824cbae866b6721f38bc29b475";
  }

  static const char* value(const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x081ce2824cbae866ULL;
  static const uint64_t static_value2 = 0xb6721f38bc29b475ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/Yolov8Inference";
  }

  static const char* value(const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header #adds timestamp \n"
"InferenceResult[] yolov8_inference #each detecte object will be appended as an inference result message.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: yolov8_msgs/InferenceResult\n"
"string class_name\n"
"int64 top\n"
"int64 left\n"
"int64 bottom\n"
"int64 right\n"
;
  }

  static const char* value(const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yolov8_inference);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Yolov8Inference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::Yolov8Inference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::Yolov8Inference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yolov8_inference[]" << std::endl;
    for (size_t i = 0; i < v.yolov8_inference.size(); ++i)
    {
      s << indent << "  yolov8_inference[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolov8_msgs::InferenceResult_<ContainerAllocator> >::stream(s, indent + "    ", v.yolov8_inference[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_YOLOV8INFERENCE_H
